CREATE TABLE `ai_question_reports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question_id` VARCHAR(64) DEFAULT NULL,
  `category` VARCHAR(64) DEFAULT NULL,
  `question_text` TEXT NOT NULL,
  `answers` LONGTEXT NOT NULL,
  `correct_index` TINYINT NOT NULL,
  `sources` LONGTEXT DEFAULT NULL,
  `origin` VARCHAR(32) DEFAULT NULL,
  `reported_at` DATETIME DEFAULT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'open',
  `reviewed_at` DATETIME DEFAULT NULL,
  `reworked_question_text` TEXT DEFAULT NULL,
  `reworked_answers` LONGTEXT DEFAULT NULL,
  `reworked_correct_index` TINYINT DEFAULT NULL,
  `reworked_sources` LONGTEXT DEFAULT NULL,
  `reworked_at` DATETIME DEFAULT NULL,
  `user_agent` TEXT DEFAULT NULL,
  `ip_address` VARCHAR(64) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_category` (`category`),
  INDEX `idx_reported_at` (`reported_at`),
  INDEX `idx_status` (`status`)
);
